# Generated by Django 5.2 on 2025-04-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('date', models.CharField(max_length=255, verbose_name='date')),
                ('total_cases', models.FloatField(verbose_name='total_cases')),
                ('new_cases', models.FloatField(verbose_name='new_cases')),
                ('total_deaths', models.FloatField(verbose_name='total_deaths')),
                ('new_deaths', models.FloatField(verbose_name='new_deaths')),
                ('total_vaccinations', models.FloatField(verbose_name='total_vaccinations')),
                ('people_vaccinated', models.FloatField(verbose_name='people_vaccinated')),
                ('people_fully_vaccinated', models.FloatField(verbose_name='people_fully_vaccinated')),
                ('new_vaccinations', models.FloatField(verbose_name='new_vaccinations')),
                ('icu_patients', models.FloatField(verbose_name='icu_patients')),
                ('hosp_patients', models.FloatField(verbose_name='hosp_patients')),
                ('total_tests', models.FloatField(verbose_name='total_tests')),
                ('new_tests', models.FloatField(verbose_name='new_tests')),
                ('positive_rate', models.FloatField(verbose_name='positive_rate')),
                ('tests_per_case', models.FloatField(verbose_name='tests_per_case')),
                ('stringency_index', models.FloatField(verbose_name='stringency_index')),
                ('population_density', models.FloatField(verbose_name='population_density')),
                ('median_age', models.FloatField(verbose_name='median_age')),
                ('aged_65_older', models.FloatField(verbose_name='aged_65_older')),
                ('aged_70_older', models.FloatField(verbose_name='aged_70_older')),
                ('gdp_per_capita', models.FloatField(verbose_name='gdp_per_capita')),
                ('diabetes_prevalence', models.FloatField(verbose_name='diabetes_prevalence')),
                ('female_smokers', models.FloatField(verbose_name='female_smokers')),
                ('male_smokers', models.FloatField(verbose_name='male_smokers')),
                ('hospital_beds_per_thousand', models.FloatField(verbose_name='hospital_beds_per_thousand')),
                ('life_expectancy', models.FloatField(verbose_name='life_expectancy')),
                ('human_development_index', models.FloatField(verbose_name='human_development_index')),
                ('population', models.FloatField(verbose_name='population')),
            ],
        ),
    ]
